<?php

namespace Modules\Application\Filament\Resources\Applications\Schemas;

use Filament\Actions\Action;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class ApplicationForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make(__('General Information'))
                    ->description(__('Basic details about the application.'))
                    ->schema([
                        TextInput::make('name')
                            ->label(__('Name'))
                            ->required()
                            ->maxLength(255)
                            ->placeholder(__('e.g. CRM System'))
                            ->live(onBlur: true)
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $username = \Illuminate\Support\Str::slug($state, '_');
                                $originalUsername = $username;
                                $latestId = \Modules\Application\Models\Application::max('id') ?? 0;
                                $count = $latestId + 1;

                                while (\Modules\Application\Models\Application::where('username', $username)->exists()) {
                                    $username = $originalUsername . '_' . $count;
                                    $count++;
                                }

                                $set('username', $username);
                            }),
                        TextInput::make('username')
                            ->label(__('Username'))
                            ->required()
                            ->maxLength(255)
                            ->unique(ignoreRecord: true)
                            ->prefixIcon('heroicon-o-user')
                            ->live(onBlur: true)
                            ->afterStateUpdated(function ($state, callable $set) {
                                $set('username', \Illuminate\Support\Str::slug($state, '_'));
                            }),
                    ])->columns(2),

                Section::make(__('Integration Details'))
                    ->description(__('Configuration for external communication.'))
                    ->schema([
                        TextInput::make('webhook_url')
                            ->label(__('Webhook URL'))
                            ->url()
                            ->activeUrl()
                            ->prefixIcon('heroicon-o-link')
                            ->placeholder('https://example.com/webhook') // URL usually not translated
                            ->columnSpanFull(),
                    ]),

                Section::make(__('Security Credentials'))
                    ->description(__('Manage authentication keys for this application.'))
                    ->schema([
                        TextInput::make('password')
                            ->label(__('Password'))
                            ->password()
                            ->revealable()
                            ->required(fn(string $operation): bool => $operation === 'create')
                            ->dehydrated(fn(?string $state) => filled($state))
                            ->helperText(__('Leave empty to keep current password if editing.'))
                            ->suffixAction(
                                Action::make('generate_password')
                                    ->icon('heroicon-o-key')
                                    ->action(function ($set) {
                                        $set('password', \Illuminate\Support\Str::random(16));
                                    })
                            ),

                        TextInput::make('secret_private_key')
                            ->label(__('Secret Private Key'))
                            ->disabled() // Read-only, generated by system or action
                            ->dehydrated(false) // Don't save if it's just for display here, or handle generation logic elsewhere
                            ->placeholder(__('Generated automatically'))
                            ->suffixAction(
                                Action::make('regenerate')
                                    ->label(__('Regenerate')) // Tooltip or proper label
                                    ->icon('heroicon-o-arrow-path')
                                    ->action(function ($set) {
                                        // Logic to regenerate key could go here, or just a placeholder for now
                                        $set('secret_private_key', \Illuminate\Support\Str::random(64));
                                    })
                            ),
                    ])->columns(2),
            ]);
    }
}
